### ISSUE TITLE
Get GUI settings from API

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-gui#118]
As seen in the process of containerizing the GUI, it might be necessary to create a way to get GUI settings from the API instead of using the ones in env variables during the build which cannot be modified later.

This will make the GUI more flexible to be used inside a container without having to build every time a setting needs to be changed. Also, it will be nice to not remove the previous way to do the setup (on build) just to avoid possible retro compatibility issues

**Comment by LuiggiTenorioK** [comment]
Configuration to update: https://autosubmit-gui.readthedocs.io/en/v4.1.0/configuration/

We can use the new API file configuration feature to make configuration easier:


```yaml
GUI:
  TOP_ANNOUNCEMENT: "Welcome to the Autosubmit GUI!"
  DARK_MODE_SWITCHER: false
  AUTHENTICATION: true
  AUTH_PROVIDES: oidc
  OIDC:
    CLIENT_ID: my_client_id
    AUTHORIZATION_ENDPOINT: http://my_auth_server/auth/ 
```
